// app/media.styles.ts
import { StyleSheet, Platform } from "react-native";

export const COLORS = {
  navy: "#0F2557",
  blue: "#1E3A8A",
  blueMid: "#2563EB",
  blueLight: "#DBEAFE",
  brown: "#7C4A1E",
  brownLight: "#F5EDE4",
  brownMid: "#A0522D",
  white: "#FFFFFF",
  bg: "#F0F4FF",
  card: "#FFFFFF",
  border: "#E2E8F0",
  textDark: "#0F172A",
  textMid: "#475569",
  textLight: "#94A3B8",
  red: "#EF4444",
  redLight: "#FEF2F2",
  green: "#10B981",
  shadow: "#0F2557",
};

export const FONTS = {
  regular: "Poppins_400Regular",
  medium: "Poppins_500Medium",
  semiBold: "Poppins_600SemiBold",
  bold: "Poppins_700Bold",
};

export const screen = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.bg },
  container: { flex: 1 },
  scroll: { flex: 1 },
  content: {
    maxWidth: 1500,
    alignSelf: "center",
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
});

export const header = StyleSheet.create({
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
    flexWrap: "wrap",
    gap: 12,
  },
  title: {
    fontSize: 26,
    fontFamily: FONTS.bold,
    color: COLORS.navy,
    letterSpacing: -0.5,
  },
  sub: {
    fontSize: 13,
    fontFamily: FONTS.regular,
    color: COLORS.textMid,
    marginTop: 2,
    marginBottom: 24,
  },
  uploadBtn: {
    backgroundColor: COLORS.blue,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    shadowColor: COLORS.blue,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  uploadBtnText: {
    color: COLORS.white,
    fontFamily: FONTS.semiBold,
    fontSize: 13,
  },
});

export const search = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 24,
    flexWrap: "wrap",
  },
  bar: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  input: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    fontFamily: FONTS.regular,
    color: COLORS.textDark,
    outlineStyle: "none" as any,
  },
});

export const stats = StyleSheet.create({
  bar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: COLORS.white,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  item: { flexDirection: "row", alignItems: "center", gap: 6 },
  text: { fontSize: 12, fontFamily: FONTS.medium, color: COLORS.textMid },
  divider: {
    width: 1,
    height: 14,
    backgroundColor: COLORS.border,
  },
});

export const grid = StyleSheet.create({
  wrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  uploadCard: {
    width: "23%",
    minWidth: 150,
    height: 220,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.blueMid,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.blueLight,
    gap: 8,
  },
  uploadIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  uploadLabel: {
    color: COLORS.blue,
    fontFamily: FONTS.semiBold,
    fontSize: 13,
    textAlign: "center",
  },
  uploadSub: {
    color: COLORS.blueMid,
    fontFamily: FONTS.regular,
    fontSize: 11,
    textAlign: "center",
    paddingHorizontal: 12,
  },
  card: {
    width: "23%",
    minWidth: 150,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  imgWrap: { width: "100%", height: 140, backgroundColor: COLORS.bg, overflow: "hidden" },
  thumb: { width: "100%", height: 140 },
  shimmer: {
    width: "100%",
    height: 140,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  badge: {
    position: "absolute",
    top: 10,
    left: 10,
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.brown,
  },
  badgeText: { color: "#fff", fontSize: 9, fontFamily: FONTS.medium },
  body: { padding: 12 },
  name: {
    fontFamily: FONTS.semiBold,
    fontSize: 13,
    color: COLORS.textDark,
    marginBottom: 4,
  },
  date: { fontSize: 10, fontFamily: FONTS.regular, color: COLORS.textLight },
  actions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  actionBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const pagination = StyleSheet.create({
  row: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 32,
    marginBottom: 8,
    flexWrap: "wrap",
  },
  btn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  btnActive: {
    backgroundColor: COLORS.blue,
    borderColor: COLORS.blue,
    shadowColor: COLORS.blue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  btnText: { fontFamily: FONTS.semiBold, fontSize: 13, color: COLORS.textMid },
  btnTextActive: { color: "#fff" },
  navBtn: {
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: "row",
    gap: 4,
  },
  navBtnDisabled: { opacity: 0.4 },
  navText: { fontFamily: FONTS.medium, fontSize: 13, color: COLORS.textMid },
  ellipsis: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: COLORS.textMid,
    marginHorizontal: 4,
  },
});

export const loading = StyleSheet.create({
  wrap: { alignItems: "center", paddingVertical: 60, gap: 12 },
  text: { fontFamily: FONTS.regular, fontSize: 14, color: COLORS.textMid },
});

export const empty = StyleSheet.create({
  wrap: { alignItems: "center", paddingVertical: 60, gap: 16 },
  iconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.border,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  title: { fontFamily: FONTS.medium, fontSize: 16, color: COLORS.textLight },
  btn: {
    backgroundColor: COLORS.blue,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
  },
  btnText: { color: "#fff", fontFamily: FONTS.semiBold, fontSize: 14 },
});

export const toast = StyleSheet.create({
  container: {
    position: "absolute",
    top: Platform.OS === "web" ? 20 : 60,
    right: 16,
    left: 16,
    zIndex: 9999,
    gap: 8,
    alignItems: "flex-end",
  },
  box: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    maxWidth: 380,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  success: { backgroundColor: COLORS.green },
  error: { backgroundColor: COLORS.red },
  msg: { flex: 1, color: "#fff", fontSize: 13, fontFamily: FONTS.medium },
});

export const dialog = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9998,
  },
  box: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 24,
    width: "90%",
    maxWidth: 320,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 10,
  },
  iconWrap: {
    width: 56, height: 56, borderRadius: 28,
    backgroundColor: COLORS.redLight,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  title: { fontSize: 18, fontFamily: FONTS.bold, color: COLORS.textDark, marginBottom: 6 },
  msg: {
    fontSize: 13, fontFamily: FONTS.regular,
    color: COLORS.textMid, textAlign: "center", marginBottom: 24,
  },
  actions: { flexDirection: "row", gap: 12, width: "100%" },
  cancelBtn: {
    flex: 1, paddingVertical: 12, borderRadius: 12,
    borderWidth: 1, borderColor: COLORS.border, alignItems: "center",
  },
  cancelText: { fontFamily: FONTS.medium, fontSize: 14, color: COLORS.textMid },
  deleteBtn: {
    flex: 1, paddingVertical: 12, borderRadius: 12,
    backgroundColor: COLORS.red, alignItems: "center",
  },
  deleteText: { fontFamily: FONTS.semiBold, fontSize: 14, color: "#fff" },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.92)",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: Platform.OS === "web" ? 20 : 50,
    paddingHorizontal: 20,
    paddingBottom: 16,
    zIndex: 10,
  },
  title: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.white,
    flex: 1,
    opacity: 0.9,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  loaderWrap: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
  },
  image: {
    width: "100%",
    height: "100%",
  },

});